CREATE TABLE IF NOT EXISTS Users
(
    user_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name varchar(20),
    login     varchar(20) NOT NULL,
    email     varchar(50) NOT NULL,
    birthday  TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Genre
(
    genre_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(20)
);
CREATE TABLE IF NOT EXISTS Rating
(
    rating_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_name varchar(20)
);

CREATE TABLE IF NOT EXISTS Films
(
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name    varchar(100) NOT NULL,
    description  varchar(200) NOT NULL,
    release_date TIMESTAMP,
    duration     integer CHECK (duration > 0),
    genre_id     integer REFERENCES Genre (genre_id),
    rating_id    INTEGER REFERENCES Rating (rating_id)
);
CREATE TABLE IF NOT EXISTS Likes
(
    like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES Films (film_id),
    user_id INTEGER REFERENCES Users (user_id)
);
CREATE TABLE IF NOT EXISTS Friends
(
    friendship_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    friend_id     INTEGER NOT NULL,
    approval   boolean
);